name: Test Path Creation

on:
  workflow_dispatch:  # 수동 실행만 (자동 스케줄 아님)

jobs:
  test-path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pandas
        run: pip install pandas

      - name: Run test.py
        run: python test.py
