name: Test Path Creation

on:
  workflow_dispatch:  # 수동 실행할 수 있게 설정

jobs:
  test-path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: List files (for debugging)
        run: ls -R
        
      - name: Run test.py
        run: python buy_on_kream/test.py

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-csv
          path: data/test_df.csv
